<?php

return
    [
        "Aceh" =>
            ["Banda Aceh",
                "Bireun",
                "Dewantara",
                "Kuala Simpang",
                "Langsa",
                "Lhokseumawe",
                "Meulaboh",
                "Sabang",
                "Sigli",
                "Subulussalam"
            ],
        "Bali" =>
            ["Denpasar",
                "Karangasem",
                "Klungkung",
                "Kuta",
                "Negara",
                "Singaraja",
                "Tabanan",
                "Ubud"
            ],
        "Bangka-Belitung" =>
            ["Manggar",
                "Mentok",
                "Pangkal Pinang",
                "Sungai Liat",
                "Tanjung Pandan",
                "Toboali-Rias"
            ],
        "Banten" =>
            ["Balaraja",
                "Cikupa",
                "Cilegon",
                "Ciputat",
                "Curug",
                "Kosambi",
                "Kresek",
                "Labuhan",
                "Pandegelang",
                "Pasarkemis",
                "Pondok Aren",
                "Rangkasbitung",
                "Sepatan",
                "Serang",
                "Serpong",
                "Tangerang",
                "Tangerang Selatan",
                "Teluknaga"
            ],
        "Bengkulu" =>
            ["Bengkulu",
                "Curup"
            ],
        "Gorontalo" =>
            ["Gorontalo"
            ],
        "Jakarta" =>
            ["Jakarta"
            ],
        "Jambi" =>
            ["Jambi",
                "Kualatungka",
                "Mendahara",
                "Simpang",
                "Sungaipenuh"
            ],
        "Jawa Barat" =>
            ["Arjawinangun",
                "Astanajapura",
                "Babakan",
                "Baleendah",
                "Bandung",
                "Banjar",
                "Banjaran",
                "Batu Jajar",
                "Bekasi",
                "Bogor",
                "Bojong Gede",
                "Caringan",
                "Ciamis",
                "Ciampea",
                "Cianjur",
                "Ciawi",
                "Cibadak",
                "Cibeureum",
                "Cibinong",
                "Cibitung",
                "Cibungbulang",
                "Cicalengka",
                "Cicuruk",
                "Cidahu",
                "Cikampek",
                "Cikarang",
                "Cikeruh",
                "Ciledug",
                "Cileungsi",
                "Cileunyi",
                "Cimahi",
                "Cimanggung",
                "Ciomas",
                "Ciparay",
                "Ciranjang",
                "Cirebon",
                "Cirebon Barat",
                "Cirebon Selatan",
                "Cirebon Utara",
                "Cisaat",
                "Cisarua",
                "Citeureup",
                "Dayeuh Kolot",
                "Depok",
                "Dramaga",
                "Garut",
                "Gunung Putri",
                "Indramayu",
                "Jamanis",
                "Jatibarang",
                "Jatiwangi",
                "Kadipaten",
                "Kadungora",
                "Karang Tengah",
                "Karangampel",
                "Karangsembung",
                "Karawang",
                "Kawalu",
                "Kelari",
                "Kemang",
                "Ketapang",
                "Klangenan",
                "Kramat Mulya",
                "Kuningan",
                "Lemahabang",
                "Lembang",
                "Leuwiliang",
                "Majalaya",
                "Majalengka",
                "Margaasih",
                "Margahayu",
                "Mundu",
                "Ngamprah",
                "Pacet",
                "Padalarang",
                "Palabuhanratu",
                "Palimanan",
                "Pamanukan",
                "Pameungpeuk",
                "Pamulang",
                "Parongpong",
                "Parung",
                "Paseh",
                "Plered",
                "Plumbon",
                "Purwakarta",
                "Rajapolah",
                "Rancaekek",
                "Rengasdengklok",
                "Sawangan",
                "Sindang",
                "Singaparna",
                "Soreang",
                "Subang",
                "Sukabumi",
                "Sukaraja",
                "Sumber",
                "Sumedang",
                "Tambun",
                "Tarogong",
                "Tasikmalaya",
                "Wanaraja",
                "Weru"
            ],
        "Jawa Tengah" =>
            ["Adiwerna",
                "Ambarawa",
                "Bae",
                "Baki",
                "Balapulang",
                "Banyumas",
                "Batang",
                "Baturaden",
                "Blora",
                "Boyolali",
                "Brebes",
                "Buaran",
                "Bulakamba",
                "Bumiayu",
                "Ceper",
                "Cepu",
                "Cilacap",
                "Colomandu",
                "Comal",
                "Delanggu",
                "Demak",
                "Dukuhturi",
                "Dukuhwaru",
                "Gatak",
                "Gebog",
                "Gombong",
                "Grogol",
                "Jaten",
                "Jati",
                "Jatibarang",
                "Jeluko",
                "Jepara",
                "Jogonalan",
                "Juwana",
                "Kalikotes",
                "Kaliwungu",
                "Karanganom",
                "Karanganyar",
                "Kartosura",
                "Kebonarum",
                "Kebumen",
                "Kedungwuni",
                "Kembaran",
                "Kendal",
                "Kersana",
                "Ketanggungan",
                "Klaten",
                "Kramat",
                "Kroya",
                "Kudus",
                "Kutoarjo",
                "Lasem",
                "Lebaksiu",
                "Magelang",
                "Majenang",
                "Margasari",
                "Mayong",
                "Mertoyudan",
                "Mlonggo",
                "Mojobo",
                "Mojolaban",
                "Mranggen",
                "Muntilan",
                "Ngawen",
                "Ngemplak",
                "Pangkah",
                "Parakan",
                "Pati",
                "Pecangakan",
                "Pedan",
                "Pekalongan",
                "Pemalang",
                "Peterukan",
                "Ponorogo",
                "Prambanan",
                "Purbalingga",
                "Purwodadi",
                "Purwokerto",
                "Purworejo",
                "Purworejo Klampok",
                "Randudongkal",
                "Rembang",
                "Salatiga",
                "Selogiri",
                "Semarang",
                "Sidareja",
                "Slawi",
                "Sragen",
                "Sukaraja",
                "Surakarta",
                "Talang",
                "Taman",
                "Tarub",
                "Tayu",
                "Tegal",
                "Temanggung",
                "Tirto",
                "Trucuk",
                "Ungaran",
                "Wanasari",
                "Wedi",
                "Welahan",
                "Weleri",
                "Wengon",
                "Wiradesa",
                "Wonogiri",
                "Wonopringgo",
                "Wonosari",
                "Wonosobo",
                "Wuradesa"
            ],
        "Jawa Timur" =>
            ["Ambulu",
                "Babat",
                "Balung",
                "Bangil",
                "Bangkalan",
                "Banyuwangi",
                "Batu",
                "Besuki",
                "Blitar",
                "Bojonegoro",
                "Bondowoso",
                "Boyolangu",
                "Buduran",
                "Candi",
                "Dampit",
                "Diwek",
                "Driyorejo",
                "Gambiran",
                "Gampengrejo",
                "Gedangan",
                "Gedek",
                "Gempol",
                "Genteng",
                "Gondang",
                "Gondanglegi",
                "Gresik",
                "Jatiroto",
                "Jember",
                "Jombang",
                "Kalianget",
                "Kamal",
                "Kanigoro",
                "Kauman",
                "Kebomas",
                "Kediri",
                "Kedungwaru",
                "Kencong",
                "Kepanjen",
                "Kertosono",
                "Kraksaan",
                "Krian",
                "Lamongan",
                "Lawang",
                "Lumajang",
                "Madiun",
                "Magetan",
                "Malang",
                "Manyar",
                "Mojoagung",
                "Mojokerto",
                "Mojosari",
                "Muncar",
                "Nganjuk",
                "Ngawi",
                "Ngoro",
                "Ngunut",
                "Paciran",
                "Pakisaji",
                "Pamekasan",
                "Panarukan",
                "Pandaan",
                "Panji",
                "Pare",
                "Pasuruan",
                "Peterongan",
                "Porong",
                "Prigen",
                "Probolinggo",
                "Sampang",
                "Sidoarjo",
                "Singojuruh",
                "Singosari",
                "Situbondo",
                "Sooko",
                "Srono",
                "Sumber Pucung",
                "Sumenep",
                "Surabaya",
                "Taman",
                "Tanggul",
                "Tanggulangin",
                "Tanjunganom",
                "Tempeh",
                "Trenggalek",
                "Tuban",
                "Tulangan",
                "Tulungagung",
                "Waru",
                "Wates",
                "Wlingi"
            ],
        "Kalimantan Barat" =>
            ["Manis Mata",
                "Pemangkat",
                "Pontianak",
                "Singkawang",
                "Sungairaya"
            ],
        "Kalimantan Selatan" =>
            ["Amuntai",
                "Banjarbaru",
                "Banjarmasin",
                "Barabai",
                "Kota Baru",
                "Martapura",
                "Pulau Sembilan"
            ],
        "Kalimantan Tengah" =>
            ["Kualakapuas",
                "Palangka Raya",
                "Pangkalanbuun",
                "Sampit"
            ],
        "Kalimantan Timur" =>
            ["Balikpapan",
                "Bontang",
                "Loa Janan",
                "Samarinda",
                "Sembakung",
                "Tanjung Redeb",
                "Tarakan"
            ],
        "Lampung" =>
            ["Bandar Lampung",
                "Gadingrejo",
                "Kota Bumi",
                "Metro",
                "Pringsewu",
                "Terbanggi Besar"
            ],
        "Maluku Utara" =>
            ["Ternate",
                "Tidore"
            ],
        "Maluku" =>
            ["Amahai",
                "Ambon",
                "Tual"
            ],
        "Nusa Tenggara Barat" =>
            ["Bima",
                "Labu Api",
                "Mataram",
                "Praya",
                "Sumbawa"
            ],
        "Nusa Tenggara Timur" =>
            ["Atambua",
                "Ende",
                "Kefamenanu",
                "Kupang",
                "Maumere",
                "Ngada Bawa",
                "Ruteng",
                "Soe",
                "Waingapu"
            ],
        "Papua Barat" =>
            ["Biak",
                "Manokwari",
                "Nabire",
                "Sorong"
            ],
        "Papua" =>
            ["Aberpura",
                "Jaya Pura",
                "Merauke",
                "Obaa"
            ],
        "Riau Kepulauan" =>
            ["Batam",
                "Kijang",
                "Tanjung Pinang"
            ],
        "Riau" =>
            ["Balaipungut",
                "Bengkalis",
                "Dumai",
                "Duri",
                "Pekan Baru",
                "Selatpanjang",
                "Tanjung Balai-Meral",
                "Tembilahan"
            ],
        "Sulawesi Barat" =>
            ["Majene",
                "Polewali"
            ],
        "Sulawesi Selatan" =>
            ["Bajeng",
                "Banggae",
                "Bone",
                "Bontonompo",
                "Galesong",
                "Makasar",
                "Maritengngae",
                "Pallangga",
                "Palopo",
                "Pangkajene",
                "Pare Pare",
                "Rantepao",
                "Singkang",
                "Sinjai",
                "Sombaopu",
                "Tanete",
                "Tempe",
                "Ujung Bulu",
                "Watang Sawitto"
            ],
        "Sulawesi Tengah" =>
            ["Baolan",
                "Luwuk",
                "Palu",
                "Poso"
            ],
        "Sulawesi Tenggara" =>
            ["Bau Bau",
                "Binongko",
                "Katobu",
                "Kendari"
            ],
        "Sulawesi Utara" =>
            ["Bitung",
                "Manado",
                "Mobagu",
                "Tomohon",
                "Tondano"
            ],
        "Sumatera Barat" =>
            ["Bukit Tinggi",
                "Padang",
                "Padang Panjang",
                "Pariaman",
                "Payakumbuh",
                "Sawah Lunto",
                "Sijunjung",
                "Solok"
            ],
        "Sumatera Selatan" =>
            ["Baturaja",
                "Lahat",
                "Lubuk Linggau",
                "Pagar Alam",
                "Palembang",
                "Prabumulih",
                "Tanjung Agung"
            ],
        "Sumatera Utara" =>
            ["Bandar",
                "Batang Kuis",
                "Belawan",
                "Binjai",
                "Deli Tua",
                "Gunung Stoli",
                "Hamparan Perak",
                "Kabanjahe",
                "Kisaran",
                "Kota Pinang",
                "Labuhan Deli",
                "Lubuk Pakam",
                "Medan",
                "Padang Sidempuan",
                "Pangkalanbrandan",
                "Pematang Siantar",
                "Perbaungan",
                "Percut Sei Tuan",
                "Rantauprapat",
                "Sei Rampah",
                "Sibolga",
                "Stabat",
                "Sunggal",
                "Tanjung Balai",
                "Tanjung Morawa",
                "Tanjung Tiram",
                "Tebingtinggi",
                "Teluk Nibung"
            ],
        "Yogyakarta" =>
            ["Bambanglipuro",
                "Banguntapan",
                "Bantul",
                "Depok",
                "Gamping",
                "Godean",
                "Jetis",
                "Kasihan",
                "Mlati",
                "Ngaglik",
                "Pandak",
                "Pundong",
                "Sewon",
                "Seyegan",
                "Sleman",
                "Srandakan",
                "Wonosari",
                "Yogyakarta"
            ]

    ];