<?php

return [
    "AED" => "AED - UAE dirham",
    "AFN" => "AFN - Afghan afghani",
    "ALL" => "ALL - Albanian lek",
    "AMD" => "AMD - Armenian dram",
    "ANG" => "ANG - Netherlands Antillean guilder",
    "AOA" => "AOA - Angolan kwanza",
    "ARS" => "ARS - Argentine peso",
    "AUD" => "AUD - Australian dollar",
    "AWG" => "AWG - Aruban florin",
    "AZN" => "AZN - Azerbaijani manat",

    "BAM" => "BAM - Bosnia and Herzegovina convertible mark",
    "BBD" => "BBD - Barbadian dollar",
    "BDT" => "BDT - Bangladeshi taka",
    "BGN" => "BGN - Bulgarian lev",
    "BHD" => "BHD - Bahraini dinar",
    "BIF" => "BIF - Burundi franc",
    "BMD" => "BMD - Bermudian dollar",
    "BND" => "BND - Brunei dollar",
    "BOB" => "BOB - Bolivian boliviano",
    "BRL" => "BRL - Brazilian real",
    "BSD" => "BSD - Bahamian dollar",
    "BTN" => "BTN - Bhutanese ngultrum",
    "BWP" => "BWP - Botswana pula",
    "BYR" => "BYR - Belarusian ruble",
    "BZD" => "BZD - Belize dollar",

    "CAD" => "CAD - Canadian dollar",
    "CDF" => "CDF - Congolese franc",
    "CHF" => "CHF - Swiss franc",
    "CLP" => "CLP - Chilean peso",
    "CNY" => "CNY - Chinese Yuan Renminbi",
    "COP" => "COP - Colombian peso",
    "CRC" => "CRC - Costa Rican colon",
    "CUP" => "CUP - Cuban peso",
    "CVE" => "CVE - Cape Verdean escudo",
    "CZK" => "CZK - Czech koruna",

    "DJF" => "DJF - Djiboutian franc",
    "DKK" => "DKK - Danish krone",
    "DOP" => "DOP - Dominican peso",
    "DZD" => "DZD - Algerian dinar",

    "EGP" => "EGP - Egyptian pound",
    "ERN" => "ERN - Eritrean nakfa",
    "ETB" => "ETB - Ethiopian birr",
    "EUR" => "EUR - European Euro",

    "FKP" => "FKP - Falkland Islands pound",
    "FJD" => "FJD - Fijian dollar",

    "GBP" => "GBP - Pound sterling",
    "GEL" => "GEL - Georgian lari",
    "GGP" => "GGP - Guernsey Pound",
    "GHS" => "GHS - Ghanaian cedi",
    "GIP" => "GIP - Gibraltar pound",
    "GMD" => "GMD - Gambian dalasi",
    "GNF" => "GNF - Guinean franc",
    "GTQ" => "GTQ - Guatemalan quetzal",
    "GYD" => "GYD - Guyanese dollar",

    "HKD" => "HKD - Hong Kong dollar",
    "HNL" => "HNL - Honduran lempira",
    "HRK" => "HRK - Croatian kuna",
    "HTG" => "HTG - Haitian gourde",
    "HUF" => "HUF - Hungarian forint",

    "IDR" => "IDR - Indonesian rupiah",
    "ILS" => "ILS - Israeli new sheqel",
    "IMP" => "IMP - Manx pound",
    "INR" => "INR - Indian rupee",
    "IQD" => "IQD - Iraqi dinar",
    "IRR" => "IRR - Iranian rial",
    "ISK" => "ISK - Icelandic krona",

    "JEP" => "JEP - Jersey pound",
    "JMD" => "JMD - Jamaican dollar",
    "JOD" => "JOD - Jordanian dinar",
    "JPY" => "JPY - Japanese yen",

    "KES" => "KES - Kenyan shilling",
    "KGS" => "KGS - Kyrgyzstani som",
    "KHR" => "KHR - Cambodian riel",
    "KMF" => "KMF - Comorian franc",
    "KPW" => "KPW - North Korean won",
    "KRW" => "KRW - South Korean won",
    "KWD" => "KWD - Kuwaiti dinar",
    "KYD" => "KYD - Cayman Islands dollar",
    "KZT" => "KZT - Kazakhstani tenge",

    "LAK" => "LAK - Lao kip",
    "LBP" => "LBP - Lebanese pound",
    "LKR" => "LKR - Sri Lankan rupee",
    "LRD" => "LRD - Liberian dollar",
    "LSL" => "LSL - Lesotho loti",
    "LYD" => "LYD - Libyan dinar",

    "MAD" => "MAD - Moroccan dirham",
    "MDL" => "MDL - Moldovan leu",
    "MGA" => "MGA - Malagasy ariary",
    "MKD" => "MKD - Macedonian denar",
    "MMK" => "MMK - Myanmar kyat",
    "MNT" => "MNT - Mongolian tugrik",
    "MOP" => "MOP - Macanese pataca",
    "MRO" => "MRO - Mauritanian ouguiya",
    "MUR" => "MUR - Mauritian rupee",
    "MVR" => "MVR - Maldivian rufiyaa",
    "MWK" => "MWK -	Malawian kwacha",
    "MXN" => "MXN - Mexican peso",
    "MYR" => "MYR - Malaysian ringgit",
    "MZN" => "MZN - Mozambican metical",

    "NAD" => "NAD - Namibian dollar",
    "NGN" => "NGN - Nigerian naira",
    "NIO" => "NIO - Nicaraguan cordoba",
    "NOK" => "NOK - Norwegian krone",
    "NPR" => "NPR - Nepalese rupee",
    "NZD" => "NZD - New Zealand dollar",

    "OMR" => "OMR - Omani rial",

    "PEN" => "PEN - Peruvian nuevo sol",
    "PGK" => "PGK - Papua New Guinean kina",
    "PHP" => "PHP - Philippine peso",
    "PKR" => "PKR - Pakistani rupee",
    "PLN" => "PLN - Polish zloty",
    "PYG" => "PYG - Paraguayan guarani",

    "QAR" => "QAR - Qatari riyal",

    "RON" => "RON - Romanian leu",
    "RSD" => "RSD - Serbian dinar",
    "RUB" => "RUB - Russian ruble",
    "RWF" => "RWF - Rwandan franc",

    "SAR" => "SAR - Saudi riyal",
    "SBD" => "SBD - Solomon Islands dollar",
    "SCR" => "SCR - Seychellois rupee",
    "SDG" => "SDG - Sudanese pound",
    "SEK" => "SEK - Swedish krona",
    "SGD" => "SGD - Singapore dollar",
    "SHP" => "SHP - Saint Helena pound",
    "SLL" => "SLL - Sierra Leonean leone",
    "SOS" => "SOS - Somali shilling",
    "SRD" => "SRD - Surinamese dollar",
    "SSP" => "SSP - South Sudanese pound",
    "STD" => "STD - Sao Tome and Principe dobra",
    "SYP" => "SYP - Syrian pound",
    "SZL" => "SZL - Swazi lilangeni",

    "THB" => "THB - Thai baht",
    "TJS" => "TJS - Tajikistani somoni",
    "TMT" => "TMT - Turkmenistani manat",
    "TND" => "TND - Tunisian dinar",
    "TOP" => "TOP - Tongan paʻanga",
    "TRY" => "TRY - Turkish lira",
    "TTD" => "TTD - Trinidad and Tobago dollar",
    "TWD" => "TWD - New Taiwan dollar",
    "TZS" => "TZS - Tanzanian shilling",

    "UAH" => "UAH - Ukrainian hryvnia",
    "UGX" => "UGX - Ugandan shilling",
    "USD" => "USD - United States dollar",
    "UYU" => "UYU - Uruguayan peso",
    "UZS" => "UZS - Uzbekistani som",

    "VEF" => "VEF - Venezuelan bolivar",
    "VND" => "VND - Vietnamese dong",
    "VUV" => "VUV - Vanuatu vatu",

    "WST" => "WST - Samoan tala",

    "XAF" => "XAF - Central African CFA franc",
    "XCD" => "XCD - East Caribbean dollar",
    "XDR" => "XDR - SDR (Special Drawing Right)",
    "XOF" => "XOF - West African CFA franc",
    "XPF" => "XPF - CFP franc",

    "YER" => "YER - Yemeni rial",

    "ZAR" => "ZAR - South African rand",
    "ZMW" => "ZMW - Zambian kwacha"
];